#ifndef YOOKAIC_CONSTANTS_H
#define YOOKAIC_CONSTANTS_H
#define RESOURCE_FOLDER "../Resources/"
#define DEFAULT_FONT_PATH RESOURCE_FOLDER "Fonts/LLT.ttc"

#define EXIT_SIGNAL 32767
#define NO_SIGNAL 0
#endif
